/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as contracts from './contracts';
export type { contracts };
import type * as contractsV3 from './contractsV3';
export type { contractsV3 };
import type * as contractsV4 from './contractsV4';
export type { contractsV4 };
